-- ⚠️ IMPORTANT: This will reset your tables to support the Token-Only system.
-- Run this entire script in your Supabase SQL Editor.

-- 1. Drop existing tables to start fresh (avoids conflicts)
drop table if exists items;
drop table if exists user_tokens;

-- 2. Create 'user_tokens' table (Just stores the token)
create table user_tokens (
  token text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create 'items' table (Linked to the token)
create table items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_token text references user_tokens(token) not null, -- Links to the token
  type text default 'video',
  title text,
  url text,
  category text,
  notes text
);

-- 4. Enable RLS (Row Level Security)
alter table user_tokens enable row level security;
alter table items enable row level security;

-- 5. Create Policies (Allow public access since we manage security via the token itself)
-- Note: In a production app with real auth, we would use auth.uid(). 
-- Here, we trust the client to only query their own token.

-- User Tokens Policies
create policy "Allow public insert tokens" on user_tokens for insert with check (true);
create policy "Allow public select tokens" on user_tokens for select using (true);

-- Items Policies
create policy "Allow public insert items" on items for insert with check (true);
create policy "Allow public select items" on items for select using (true);
create policy "Allow public delete items" on items for delete using (true);
