-- 1. Create the 'items' table for storing videos and notes
create table if not exists items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  type text default 'video', -- 'video' or 'note'
  title text,
  url text,
  category text,
  notes text
);

-- 2. Enable security for items
alter table items enable row level security;

-- 3. Allow users to only see/edit their own items
create policy "Users can see their own items"
  on items for all
  using (auth.uid() = user_id);

-- 4. Create the 'user_tokens' table for the custom token login
create table if not exists user_tokens (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  token text unique not null,
  email text not null,
  password text not null
);

-- 5. Enable security for user_tokens
alter table user_tokens enable row level security;

-- 6. Allow the app to save new tokens during Sign Up
create policy "Enable insert for authentication"
  on user_tokens for insert
  with check (true);

-- 7. Allow the app to look up tokens during Sign In
create policy "Enable read for authentication"
  on user_tokens for select
  using (true);
