-- ⚠️ IMPORTANT: Run this entire script in your Supabase SQL Editor.
-- It resets everything and adds support for Image Uploads (Screenshots).

-- 1. Drop existing tables to start fresh
drop table if exists items;
drop table if exists user_tokens;

-- 2. Create 'user_tokens' table
create table user_tokens (
  token text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create 'items' table (Now with image_url)
create table items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_token text references user_tokens(token) not null,
  type text default 'video',
  title text,
  url text,
  category text,
  notes text,
  image_url text -- New column for screenshots
);

-- 4. Enable RLS
alter table user_tokens enable row level security;
alter table items enable row level security;

-- 5. Create Policies
create policy "Allow public insert tokens" on user_tokens for insert with check (true);
create policy "Allow public select tokens" on user_tokens for select using (true);

create policy "Allow public insert items" on items for insert with check (true);
create policy "Allow public select items" on items for select using (true);
create policy "Allow public delete items" on items for delete using (true);

-- 6. STORAGE SETUP (For Screenshots)
-- Note: You must create a bucket named 'screenshots' in the Supabase Dashboard > Storage
-- This SQL attempts to insert it, but it's safer to do it in the dashboard if this fails.
insert into storage.buckets (id, name, public) 
values ('screenshots', 'screenshots', true)
on conflict (id) do nothing;

-- Allow public access to the 'screenshots' bucket
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'screenshots' );

create policy "Public Upload"
on storage.objects for insert
with check ( bucket_id = 'screenshots' );
