-- ============================================================
-- EXPENSE TABLE VIEW - COMPLETE SUPABASE SETUP
-- ============================================================
-- Run this in Supabase SQL Editor to enable Excel-like expense table
-- This ensures all necessary columns exist for the expense table feature
-- ============================================================

-- ============================================================
-- 1. ENSURE ITEMS TABLE HAS ALL EXPENSE-RELATED COLUMNS
-- ============================================================

-- Add 'amount' column for expense amounts (if not exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'items' AND column_name = 'amount'
  ) THEN
    ALTER TABLE items ADD COLUMN amount NUMERIC(10, 2) DEFAULT 0;
  END IF;
END $$;

-- Add 'is_income' column to differentiate income vs expense (if not exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'items' AND column_name = 'is_income'
  ) THEN
    ALTER TABLE items ADD COLUMN is_income BOOLEAN DEFAULT false;
  END IF;
END $$;

-- Add 'expense_status' column to track pending/billed status (if not exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'items' AND column_name = 'expense_status'
  ) THEN
    ALTER TABLE items ADD COLUMN expense_status TEXT DEFAULT 'pending';
  END IF;
END $$;

-- Add 'billed_at' timestamp for when expense was billed (if not exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'items' AND column_name = 'billed_at'
  ) THEN
    ALTER TABLE items ADD COLUMN billed_at TIMESTAMP WITH TIME ZONE;
  END IF;
END $$;

-- Add 'category' column for expense categorization (if not exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'items' AND column_name = 'category'
  ) THEN
    ALTER TABLE items ADD COLUMN category TEXT;
  END IF;
END $$;

-- ============================================================
-- 2. CREATE PAYMENT HISTORY TABLE (if not exists)
-- ============================================================

CREATE TABLE IF NOT EXISTS payment_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_token TEXT NOT NULL,
  bill_id TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  total_amount NUMERIC(10, 2) NOT NULL,
  item_count INTEGER NOT NULL,
  items JSONB NOT NULL,
  notes TEXT
);

-- Enable Row Level Security
ALTER TABLE payment_history ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can insert their own bills" ON payment_history;
DROP POLICY IF EXISTS "Users can view their own bills" ON payment_history;
DROP POLICY IF EXISTS "Users can delete their own bills" ON payment_history;
DROP POLICY IF EXISTS "Users can update their own bills" ON payment_history;

-- Create policies for payment_history
CREATE POLICY "Users can insert their own bills"
  ON payment_history FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Users can view their own bills"
  ON payment_history FOR SELECT
  USING (true);

CREATE POLICY "Users can delete their own bills"
  ON payment_history FOR DELETE
  USING (true);

CREATE POLICY "Users can update their own bills"
  ON payment_history FOR UPDATE
  USING (true);

-- ============================================================
-- 3. CREATE INDEX FOR FASTER QUERIES
-- ============================================================

-- Index on expense_status for quick filtering
CREATE INDEX IF NOT EXISTS idx_items_expense_status 
  ON items(expense_status) 
  WHERE type = 'expense';

-- Index on type for expense filtering
CREATE INDEX IF NOT EXISTS idx_items_type 
  ON items(type);

-- Index on created_at for sorting by date
CREATE INDEX IF NOT EXISTS idx_items_created_at 
  ON items(created_at DESC);

-- Index on user_token in items for multi-user filtering
CREATE INDEX IF NOT EXISTS idx_items_user_token 
  ON items(user_token);

-- Index on payment_history user_token
CREATE INDEX IF NOT EXISTS idx_payment_history_user_token 
  ON payment_history(user_token);

-- ============================================================
-- 4. CREATE HELPFUL VIEWS (OPTIONAL)
-- ============================================================

-- View for pending expenses only
CREATE OR REPLACE VIEW pending_expenses AS
SELECT 
  id,
  user_token,
  title,
  notes,
  amount,
  is_income,
  expense_status,
  category,
  metadata,
  created_at,
  billed_at
FROM items
WHERE type = 'expense' 
  AND (expense_status = 'pending' OR expense_status IS NULL);

-- View for expense summary statistics
CREATE OR REPLACE VIEW expense_summary AS
SELECT 
  user_token,
  COUNT(*) as total_expenses,
  COUNT(*) FILTER (WHERE expense_status = 'pending') as pending_count,
  COUNT(*) FILTER (WHERE expense_status = 'billed') as billed_count,
  SUM(amount) FILTER (WHERE NOT is_income) as total_expense_amount,
  SUM(amount) FILTER (WHERE is_income) as total_income_amount,
  SUM(CASE 
    WHEN is_income THEN amount 
    ELSE -amount 
  END) as net_balance
FROM items
WHERE type = 'expense'
GROUP BY user_token;

-- ============================================================
-- 5. VERIFICATION QUERIES (Run these to check setup)
-- ============================================================

-- Check if all columns exist
-- SELECT column_name, data_type 
-- FROM information_schema.columns 
-- WHERE table_name = 'items' 
--   AND column_name IN ('amount', 'is_income', 'expense_status', 'billed_at', 'category')
-- ORDER BY column_name;

-- Check payment_history table
-- SELECT * FROM payment_history LIMIT 5;

-- Check pending expenses view
-- SELECT * FROM pending_expenses LIMIT 10;

-- ============================================================
-- ✅ SETUP COMPLETE!
-- ============================================================
-- Your database is now ready for the Excel-like expense table view
-- All necessary columns, tables, indexes, and views are created
-- ============================================================
