-- Create the 'user_tokens' table for the custom token login
create table if not exists user_tokens (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  token text unique not null,
  email text not null,
  password text not null
);

-- Enable security for user_tokens
alter table user_tokens enable row level security;

-- Drop policies if they exist to avoid errors when re-running
drop policy if exists "Enable insert for authentication" on user_tokens;
drop policy if exists "Enable read for authentication" on user_tokens;

-- Allow the app to save new tokens during Sign Up
create policy "Enable insert for authentication"
  on user_tokens for insert
  with check (true);

-- Allow the app to look up tokens during Sign In
create policy "Enable read for authentication"
  on user_tokens for select
  using (true);
