-- Create payment_history table to store expense bills
CREATE TABLE IF NOT EXISTS payment_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_token TEXT NOT NULL,
  bill_id TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  total_amount NUMERIC(10, 2) NOT NULL,
  item_count INTEGER NOT NULL,
  items JSONB NOT NULL,  -- Store the full expense items
  notes TEXT  -- Optional notes for the bill
);

-- Enable security for payment_history
ALTER TABLE payment_history ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can insert their own bills" ON payment_history;
DROP POLICY IF EXISTS "Users can view their own bills" ON payment_history;
DROP POLICY IF EXISTS "Users can delete their own bills" ON payment_history;

-- Allow users to insert their own bills
CREATE POLICY "Users can insert their own bills"
  ON payment_history FOR INSERT
  WITH CHECK (true);

-- Allow users to view only their own bills
CREATE POLICY "Users can view their own bills"
  ON payment_history FOR SELECT
  USING (true);

-- Allow users to delete their own bills
CREATE POLICY "Users can delete their own bills"
  ON payment_history FOR DELETE
  USING (true);

-- Add expense_status column to items table if it doesn't exist
-- This will track if an expense is 'pending' or 'billed'
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'items' AND column_name = 'expense_status'
  ) THEN
    ALTER TABLE items ADD COLUMN expense_status TEXT DEFAULT 'pending';
  END IF;
END $$;

-- Add billed_at column to track when expense was billed
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'items' AND column_name = 'billed_at'
  ) THEN
    ALTER TABLE items ADD COLUMN billed_at TIMESTAMP WITH TIME ZONE;
  END IF;
END $$;
